[package]
name = "smaf-cli"
version.workspace = true
edition.workspace = true
description = "A command-line player for Yamaha SMAF audio files"
repository.workspace = true
license.workspace = true

[dependencies]
async-trait = { version = "^0.1", default-features = false }
midir = { version = "^0.11", default-features = false }
rodio = { version = "^0.20", default-features = false }
tokio = { version = "^1.52", features = ["rt", "macros", "time"], default-features = false }

smaf.workspace = true
smaf-player.workspace = true
