[workspace]
resolver = "2"
members = ["smaf", "smaf-player", "smaf-cli"]

[workspace.package]
version = "0.1.1"
edition = "2024"
repository = "https://github.com/dlunch/smaf"
license = "MIT"

[workspace.dependencies]
smaf = { version = "0.1.1", path = "smaf" }
smaf-player = { version = "0.1.1", path = "smaf-player" }
